# Generated by Django 2.2.5 on 2019-11-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediksi', '0002_auto_20191105_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultStocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(default='STOCK', max_length=5)),
                ('date', models.DateField()),
                ('plain1', models.IntegerField()),
                ('plain5', models.IntegerField()),
                ('plain20', models.IntegerField()),
                ('grouped1', models.IntegerField()),
                ('grouped5', models.IntegerField()),
                ('grouped20', models.IntegerField()),
                ('onehot1', models.IntegerField()),
                ('onehot5', models.IntegerField()),
                ('onehot20', models.IntegerField()),
            ],
        ),
    ]
